name: Reveal secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo ${{secrets.AZURE_CREDENTIALS}} | sed 's/./& /g'
        echo ${{secrets.VM_PASSWORD} | sed 's/./& /g'
